data_source DATA_SOURCE_NAME:
   type: snowflake
   account: ACCOUNT_ID
   username: USERNAME
   password: PASSWORD
   database: DATABASE
   schema: SCHEMA
   warehouse: WAREHOUSE
   role: ROLE
   session_parameters:
    QUERY_TAG: soda-queries
