config:
  check_type: database
  slack_token: XXXXXXXXXXXXXXXX
  slack_channels: data-quality-notifications
  source_config:
    host: xxx.xxx.xxx.xxx
    user: yyyy
    password: zzzz
  data_test_files: soda_checks.yml
  data_test_vars: yyyy-MM-dd
